//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_View
    {
        public int Id { get; set; }
        public string Customer_Name { get; set; }
        public string Store_Name { get; set; }
        public string Product_Name { get; set; }
        public string OrderDate { get; set; }
        public int ItemCount { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal ListPrice { get; set; }
    }
}
